repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: forbid-new-submodules
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: check-added-large-files
  - id: check-symlinks
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: end-of-file-fixer
#  - id: check-json
#  - id: check-xml
#  - id: check-yaml
# - repo: https://github.com/willthames/ansible-lint.git
#   sha: v3.4.17
#   hooks:
#   - id: ansible-lint
#     args: ['--exclude=required-roles', '-R', '-r tools/ansible-lint-rules']
#     files: \.yml$
